// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using MvvmCross.iOS.Views.Presenters.Attributes;
using SuspilneKazky.ViewModels;
using UIKit;

namespace SuspilneKazky.iOS
{
    [MvxFromStoryboard("Main")]
    [MvxTabPresentation(WrapInNavigationController = true, TabIconName = "home", TabName = "Stories")]
    public partial class StoriesViewController : MvxViewController<StoriesViewModel>
	{
		public StoriesViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
